run_name: dinov3_wam_robosuite
training:
  seed: 0
  epochs: 50
  batch_size: 128
  save_every_x_epoch: 10
  encoder_lr: 0.00015
  predictor_lr: 0.0005
  action_encoder_lr: 0.0005
  num_workers: 4
img_size: 256
frameskip: 8
train_data_path:
- data/NutAssemblyRound/success_rollout
- data/NutAssemblySquare/success_rollout
- data/PickPlaceBread/success_rollout
- data/PickPlaceCan/success_rollout
- data/PickPlaceCereal/success_rollout
- data/PickPlaceMilk/success_rollout
- data/Stack/success_rollout
val_data_path:
- data/NutAssemblyRound/success_rollout
- data/NutAssemblySquare/success_rollout
- data/PickPlaceBread/success_rollout
- data/PickPlaceCan/success_rollout
- data/PickPlaceCereal/success_rollout
- data/PickPlaceMilk/success_rollout
- data/Stack/success_rollout
view_names:
- agentview
- robot0_eye_in_hand
source_view_names:
- agentview
- robot0_eye_in_hand
target_view_names:
- agentview
original_img_size: 256
cropped_img_size: 224
action_emb_dim: 7
proprio_emb_dim: 32
policy_ckpt_path: null
proprio:
  Lift:
    state_dim: 32
    nq: 16
    nv: 15
    proprio_dim: 14
    indices:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
  Stack:
    state_dim: 45
    nq: 23
    nv: 21
    proprio_dim: 14
    indices:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 24
    - 25
    - 26
    - 27
    - 28
    - 29
    - 30
  NutAssemblyRound:
    state_dim: 45
    nq: 23
    nv: 21
    proprio_dim: 14
    indices:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 24
    - 25
    - 26
    - 27
    - 28
    - 29
    - 30
  NutAssemblySquare:
    state_dim: 45
    nq: 23
    nv: 21
    proprio_dim: 14
    indices:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 24
    - 25
    - 26
    - 27
    - 28
    - 29
    - 30
  PickPlaceBread:
    state_dim: 71
    nq: 37
    nv: 33
    proprio_dim: 14
    indices:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 38
    - 39
    - 40
    - 41
    - 42
    - 43
    - 44
  PickPlaceCan:
    state_dim: 71
    nq: 37
    nv: 33
    proprio_dim: 14
    indices:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 38
    - 39
    - 40
    - 41
    - 42
    - 43
    - 44
  PickPlaceCereal:
    state_dim: 71
    nq: 37
    nv: 33
    proprio_dim: 14
    indices:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 38
    - 39
    - 40
    - 41
    - 42
    - 43
    - 44
  PickPlaceMilk:
    state_dim: 71
    nq: 37
    nv: 33
    proprio_dim: 14
    indices:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 38
    - 39
    - 40
    - 41
    - 42
    - 43
    - 44
use_layernorm: true
use_crop: true
abs_action: false
normalize_action: true
num_hist: 1
num_pred: 1
action_loss_weight: 1.0
has_predictor: true
use_pretrained_encoder: true
encoder_ckpt_path: null
predictor_ckpt_path: null
proprio_indices: null
proprio_map:
  NutAssemblyRound:
    indices:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 24
    - 25
    - 26
    - 27
    - 28
    - 29
    - 30
  NutAssemblySquare:
    indices:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 24
    - 25
    - 26
    - 27
    - 28
    - 29
    - 30
  Stack:
    indices:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 24
    - 25
    - 26
    - 27
    - 28
    - 29
    - 30
  PickPlaceBread:
    indices:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 38
    - 39
    - 40
    - 41
    - 42
    - 43
    - 44
  PickPlaceCan:
    indices:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 38
    - 39
    - 40
    - 41
    - 42
    - 43
    - 44
  PickPlaceCereal:
    indices:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 38
    - 39
    - 40
    - 41
    - 42
    - 43
    - 44
  PickPlaceMilk:
    indices:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 38
    - 39
    - 40
    - 41
    - 42
    - 43
    - 44
max_trajectories: 100
causal_action_chunks: true
model:
  _target_: robosuite.discriminator.dyn_disc.models.visual_dynamics.VisualDynamicsModel
  image_size: 256
  num_hist: 1
  num_pred: 1
  train_encoder: false
  train_predictor: true
debug: false
env:
  name: hdf5
  dataset_class: robosuite.discriminator.dyn_disc.data.HDF5DynamicsModelDataset
  train_data_path:
  - data/NutAssemblyRound/success_rollout
  - data/NutAssemblySquare/success_rollout
  - data/PickPlaceBread/success_rollout
  - data/PickPlaceCan/success_rollout
  - data/PickPlaceCereal/success_rollout
  - data/PickPlaceMilk/success_rollout
  - data/Stack/success_rollout
  val_data_path:
  - data/NutAssemblyRound/success_rollout
  - data/NutAssemblySquare/success_rollout
  - data/PickPlaceBread/success_rollout
  - data/PickPlaceCan/success_rollout
  - data/PickPlaceCereal/success_rollout
  - data/PickPlaceMilk/success_rollout
  - data/Stack/success_rollout
  view_names:
  - agentview
  - robot0_eye_in_hand
  encoder_type: resnet
  return_rewards: false
  action_dim: 7
  proprio_dim: 14
  original_img_size: 256
  cropped_img_size: 224
  action_emb_dim: 7
  proprio_emb_dim: 32
  policy_ckpt_path: null
  use_cache: false
  cache_dir: data/.lpb_score_preprocessed_cache
  shape_obs: null
encoder:
  _target_: robosuite.discriminator.dyn_disc.models.dinov3_encoder.DINOv3Encoder
  model_path: data/pretrained/dinov3-vitl16-pretrain-lvd1689m
  emb_dim: 382
  pooled_grid_size: 4
  freeze_backbone: true
  train_projection: true
  image_size: 224
action_encoder:
  _target_: robosuite.discriminator.dyn_disc.models.proprio.ProprioceptiveEmbedding
  num_frames: 1
  tubelet_size: 1
proprio_encoder:
  _target_: robosuite.discriminator.dyn_disc.models.proprio.ProprioceptiveEmbedding
  num_frames: 1
  tubelet_size: 1
predictor:
  _target_: robosuite.discriminator.dyn_disc.models.vit.ViTPredictor
  depth: 6
  heads: 16
  mlp_dim: 2048
  dropout: 0.1
  emb_dropout: 0
  pool: mean
prior_in_chans: 14
action_dim_per_step: 7
