defaults:
  - eval_flow
  - _self_

policy_type: "flow"   # or dummy when testing

intervention:
  directory: "/home/dodo/Documents/DAggar/robosuite/data/PandaLift/intervention"
  environment: "Lift"
  robots: ["Panda"]
  config: "default"
  arm: "right"
  camera: ["agentview"]
  controller: null
  device: "spacemouse"
  pos_sensitivity: 1.0
  rot_sensitivity: 1.0
  renderer: "mjviewer"
  max_fr: 20
  reverse_xy: false
  goal_update_mode: "target"
  img_height: 256
  img_width: 256
  cool_down_second: 1.5