name: lift_image

image_shape: [3, 224, 224]

shape_meta: &shape_meta
  obs:
    agentview_image:
      shape: ${....image_shape}
      type: rgb
    robot0_eef_pos:
      shape: [3]
      type: low_dim
    robot0_eef_quat:
      shape: [4]
      type: low_dim
    robot0_gripper_qpos:
      shape: [2]
      type: low_dim
    robot0_joint_pos:
      shape: [7]
      type: low_dim
    # every task should have this, set manually
    ee_pose:
      shape: [7]
      type: low_dim
  action: 
    shape: [7]

env_runner:
  _target_: env_runner.robosuite_image_runner.robosuiteImageRunner
  max_steps: 600

env_runner_dummy:
  _target_: diffusion_policy.env_runner.dummy_runner.DummyRunner

dataset:
  _target_: diffusion_policy.dataset.robosuite.robosuite_image_dataset.RobosuiteImageDataset
  zarr_path: ${...dataset_path}
  horizon: ${...horizon}
  pad_before: ${eval:'${...n_obs_steps}-1'}
  pad_after: ${eval:'${...n_action_steps}-1'}
  seed: 42
  val_ratio: 0.00
  max_train_episodes: 100000
  n_obs_steps: ${...n_obs_steps}
  shape_meta: ${shape_meta}
  random_crop: True
  color_jitter: True
  image_shape: ${..image_shape}

env:
  output: "/home/dodo/Documents/DAggar/robosuite/robosuite/armada/data/tmp/${name}"
  
  environment: "Lift"
  robots: ["Panda"]
  config: "default"
  arm: "right"
  
  camera: ["agentview", "robot0_eye_in_hand"]
  resolution: [224, 224] # [H, W]
  
  controller: null
  device: "keyboard"  # keyboard, spacemouse, dualsense, mjgui
  pos_sensitivity: 1.0
  rot_sensitivity: 1.0
  reverse_xy: False   # for DualSense only
  
  renderer: "mjviewer"
  max_fr: 20
  goal_update_mode: "target"