seed: 42

policy_ckpt: "./checkpoints/PandaLift/flow/BC_warmup/flow_policy_ep0040_20260303_135632.pt"
save_dir: "./checkpoints/PandaLift/discriminator/intervention_train"

train_eps: -1

camera: "agentview"
image_size: 128
history_len: -1  # <=0 means auto from policy checkpoint

data:
  intervention_dir: "./data/PandaLift/intervention"
  expert_dir: "./data/PandaLift/expert"
  normalize_with_policy_stats: true

labels:
  window_before: 2
  window_after: 2

model:
  hidden_dim: 256
  dropout: 0.1

train:
  device: "cuda"
  batch_size: 128
  num_workers: 16
  lr: 1e-4
  weight_decay: 1e-6
  epochs: 50
  grad_clip_norm: 1.0
  freeze_policy_backbone: true

eval:
  eval_ratio: 0.2
  batch_size: 256
  threshold: 0.7

save_freq: 5
