defaults:
  - eval_flow
  - _self_

policy_type: "flow" # or dummy for random testing

fail_rollout:
  directory: "/home/dodo/Documents/DAggar/robosuite/data/PandaLift/fail_rollout"
  environment: "Lift"
  robots: ["Panda"]
  config: "default"
  arm: "right"
  camera: ["agentview"]
  controller: null
  device: "keyboard"
  pos_sensitivity: 1.0
  rot_sensitivity: 1.0
  renderer: "mjviewer"
  max_fr: 20
  img_height: 256
  img_width: 256
  max_steps: 300
  target_failures: -1
