defaults:
  - flow
  - _self_

# Dataset & Paths
data_dir: "/home/dodo/Documents/DAggar/robosuite/data/PandaLift"
save_dir: "/home/dodo/Documents/DAggar/robosuite/checkpoints/flow/BC_warmup"

seed: 42

camera: "agentview"
history_len: 4
chunk_size: 8
image_size: 128
stride: 1

train:
  batch_size: 256
  num_workers: 16
  lr: 2e-4
  weight_decay: 1e-6
  epochs: 200
  seed: 0
  device: "cuda"
  dropout: 0.1

# logging & checkpointing
log_every: 50
save_freq: 10
uf_low: 0.2
uf_high: 0.4
ema_decay: 0.999